---

################################
# APPDATA
################################

- name: Create znc appdata directory
  ansible.builtin.file:
    path: '{{ autobrr_znc_paths_location }}'
    state: directory
    owner: '{{ autobrr_znc_env_puid }}'
    group: '{{ autobrr_znc_env_pgid }}'
    mode: '0755'

- name: Create znc config directory
  ansible.builtin.file:
    path: '{{ autobrr_znc_paths_location }}/config'
    state: directory
    owner: '{{ autobrr_znc_env_puid }}'
    group: '{{ autobrr_znc_env_pgid }}'
    mode: '0755'

################################
# CONTAINER
################################

- name: Create ZNC container
  when: (not autobrr_toggles_enable_traefik) or (not autobrr_znc_traefik_is_enabled)
  community.docker.docker_container:
    name: '{{ autobrr_znc_basics_name }}'
    image: '{{ autobrr_znc_basics_image_repo }}:{{ autobrr_znc_basics_image_tag }}'
    networks: '{{ autobrr_znc_docker_networks }}'
    env:
      PUID: '{{ autobrr_znc_env_puid }}'
      PGID: '{{ autobrr_znc_env_pgid }}'
      TZ: '{{ autobrr_znc_env_timezone }}'
    ports:
      - '{{ autobrr_znc_ports_host }}:{{ autobrr_znc_ports_cont }}'
    volumes: '{{ autobrr_znc_binds_config_mapping }}'
    restart_policy: '{{ autobrr_znc_basics_restart_policy }}'

- name: Create ZNC traefik container
  when:
    - autobrr_toggles_enable_traefik
    - autobrr_znc_traefik_is_enabled
  community.docker.docker_container:
    name: '{{ autobrr_znc_basics_name }}'
    image: '{{ autobrr_znc_basics_image_repo }}:{{ autobrr_znc_basics_image_tag }}'
    networks: '{{ autobrr_znc_docker_networks }}'
    env:
      PUID: '{{ autobrr_znc_env_puid }}'
      PGID: '{{ autobrr_znc_env_pgid }}'
      TZ: '{{ autobrr_znc_env_timezone }}'
    labels: '{{ autobrr_znc_traefik_labels }}'
    ports:
      - '{{ autobrr_znc_ports_host }}:{{ autobrr_znc_ports_cont }}'
    volumes: '{{ autobrr_znc_binds_config_mapping }}'
    restart_policy: '{{ autobrr_znc_basics_restart_policy }}'
