---

################################
# CLEAN UP
################################

- name: Register thelounge container
  community.docker.docker_container_info:
    name: '{{ autobrr_thelounge_basics_name }}'
  register: autobrr_thelounge_existing_container_result

- name: Remove existing thelounge container
  when: autobrr_thelounge_existing_container_result.exists
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ autobrr_thelounge_basics_name }}'
    state: absent
    stop_timeout: 10
  register: remove_autobrr_thelounge_docker
  retries: 5
  delay: 10
  until: remove_autobrr_thelounge_docker is succeeded

################################
# APPDATA
################################

- name: Create thelounge appdata directory
  ansible.builtin.file:
    path: '{{ autobrr_thelounge_paths_location }}'
    state: directory
    owner: '{{ autobrr_thelounge_env_puid }}'
    group: '{{ autobrr_thelounge_env_pgid }}'
    mode: '0755'

- name: Create thelounge config directory
  ansible.builtin.file:
    path: '{{ autobrr_thelounge_paths_location }}/config'
    state: directory
    owner: '{{ autobrr_thelounge_env_puid }}'
    group: '{{ autobrr_thelounge_env_pgid }}'
    mode: '0755'

################################
# CONTAINER
################################

- name: Create thelounge container
  when: (not autobrr_toggles_enable_traefik) or (not autobrr_thelounge_traefik_is_enabled)
  community.docker.docker_container:
    name: '{{ autobrr_thelounge_basics_name }}'
    image: '{{ autobrr_thelounge_basics_image_repo }}:{{ autobrr_thelounge_basics_image_tag }}'
    networks: '{{ autobrr_thelounge_docker_networks }}'
    env:
      PUID: '{{ autobrr_thelounge_env_puid }}'
      PGID: '{{ autobrr_thelounge_env_pgid }}'
      TZ: '{{ autobrr_thelounge_env_timezone }}'
    ports:
      - '{{ autobrr_thelounge_ports_host }}:{{ autobrr_thelounge_ports_cont }}'
    volumes: '{{ autobrr_thelounge_binds_config_mapping }}'
    restart_policy: '{{ autobrr_thelounge_basics_restart_policy }}'

- name: Create thelounge traefik container
  when:
    - autobrr_toggles_enable_traefik
    - autobrr_thelounge_traefik_is_enabled
  community.docker.docker_container:
    name: '{{ autobrr_thelounge_basics_name }}'
    image: '{{ autobrr_thelounge_basics_image_repo }}:{{ autobrr_thelounge_basics_image_tag }}'
    networks: '{{ autobrr_thelounge_docker_networks }}'
    env:
      PUID: '{{ autobrr_thelounge_env_puid }}'
      PGID: '{{ autobrr_thelounge_env_pgid }}'
      TZ: '{{ autobrr_thelounge_env_timezone }}'
    labels: '{{ autobrr_thelounge_traefik_labels }}'
    ports:
      - '{{ autobrr_thelounge_ports_host }}:{{ autobrr_thelounge_ports_cont }}'
    volumes: '{{ autobrr_thelounge_binds_config_mapping }}'
    restart_policy: '{{ autobrr_thelounge_basics_restart_policy }}'
